#indentation is relevant!
#VERSION: 1.0.1-forever-alone


jenkins:

 build: ./jenkins
 restart: always
 ports:
 - "8033:8033"


# nexus:
#   build: ./nexus
#   ports:
#     - "8081:8081"
#
#jenkins:
#   build: ./jenkins-ci
##   links:
##      - nexus:nexus
#   ports:
#     - "8080:8080"