#indentation is relevant!
#VERSION: 1.0.1-forever-alone
teamcity:

 build: ./teamcity
 restart: always
 volumes:
 - "/root:/root"
 ports:
 - "8111:8111"
 - "9090:9090"

# nexus:
#   build: ./nexus
#   ports:
#     - "8081:8081"
#
#jenkins:
#   build: ./jenkins-ci
##   links:
##      - nexus:nexus
#   ports:
#     - "8080:8080"